-
  hosts: 
#    - forestrootpdc
#  - forestrootrdc
  - childdomainpdc
#    - childdomainrdc
#    - rootca
#    - subca
  gather_facts: yes
  vars:
    ansible_user: 
    ansible_password: 
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: Refresh facts 
      setup:
    - name: Print ansible_facts
      debug:
        var: ansible_facts
#    - name: Print some debug information 
#      vars: 
#        msg: |
#          HOST Variables ("hostvars"):
#          --------------------------------
#          {{ hostvars | to_nice_yaml | trim }} 
#      debug: 
#        msg: "{{ msg.split('\n') }}"   
