- 
  hosts: localhost
  connection: local
  vars:
    file: vars.yml
  vars_files:
    - "{{ file }}"
  roles:
#    - clonevm
#    - vmwinrm
    - template
  ignore_errors: no

- 
  hosts: 
    - forestrootpdc
    - forestrootrdc
    - childdomainpdc
    - childdomainrdc
  gather_facts: yes
  vars:
    file: vars.yml
    ignore_errors: no
    ansible_user: Administrator
    ansible_password: VMware1!
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore
  vars_files: 
    - "{{ file }}"
  roles:
    - dc
  ignore_errors: no