- name: Set DNS Server facts for Root Domain
  set_fact:
    rootdnsserver: "{{ item.dns }}"
  loop: "{{ dns_servers }}"
  when: item.domain == "forestroot"

- name: Show DNS Servers
  debug:
    var: rootdnsserver

- name: Set DNS Server facts for Child Domain
  set_fact:
    childdnsserver: "{{ item.dns }}"
  loop: "{{ dns_servers }}"
  when: item.domain == "childdomain"

- name: Show DNS Servers Part Deux
  debug:
    var: childdnsserver

- name: Create jinja2 task file for Root PDC
  template:
    src: 'roles/template/templates/CreateADRootDC1.j2'
    dest: 'roles/dc/files/{{ item.name }}-CreateADRootDC1.ps1'
  loop: "{{ vms }}"
  when: item.tags.0 == "forestrootpdc"

- name: Create jinja2 task file for Root RDC
  template:
    src: 'roles/template/templates/ConfigureADNextDC.j2'
    dest: 'roles/dc/files/{{ item.name }}-ConfigureADNextDC.ps1'
  loop: "{{ vms }}"
  when: item.tags.0 == "forestrootrdc"

- name: Create jinja2 task file for Child PDC
  template:
    src: 'roles/template/templates/CreateADChildDomainDC1.j2'
    dest: 'roles/dc/files/{{ item.name }}-CreateADChildDomainDC1.ps1'
  loop: "{{ vms }}"
  when: item.tags.0 == "childdomainpdc"

- name: Create jinja2 task file for Child RDC
  template:
    src: 'roles/template/templates/ConfigureChildADNextDC.j2'
    dest: 'roles/dc/files/{{ item.name }}-ConfigureChildADNextDC.ps1'
  loop: "{{ vms }}"
  when: item.tags.0 == "childdomainrdc"
