---
- name: Create the parent folders
  vcenter_folder:
    hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password}}"
    validate_certs: False
    datacenter: "{{ vcenter_datacenter }}"
    folder_name: "{{ item.folder_name }}"
    parent_folder: "{{ item.parent_folder }}"
  with_items:
    "{{ vcenter_folders }}"
  when: 
    - vcenter_folders[item].parent_folder is not defined

- name: Create the sub folders
  vcenter_folder:
    hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password}}"
    validate_certs: False
    datacenter: "{{ vcenter_datacenter }}"
    folder_name: "{{ item.folder_name }}"
    parent_folder: "{{ item.parent_folder }}"
  with_items:
    "{{ vcenter_folders }}"
  when: 
    - vcenter_folders[item].parent_folder is defined

- name: Clone the template with single DNS entry
  vmware_guest:
    hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password}}"
    validate_certs: False
    name: "{{ item.name }}"
    template: "{{ template_name }}"
    datacenter: "{{ vcenter_datacenter }}"
    folder: "{{ item.folder }}"
    state: poweredon
    cluster: "{{ vcenter_cluster }}"
    networks:
      - name: "{{ item.networks.0.name }}"
        ip: "{{ item.networks.0.ip }}"
        netmask: "{{ item.networks.0.netmask }}"
        gateway: "{{ item.networks.0.gateway }}"
        domain: "{{ item.networks.0.domain }}"
        dns_servers:
        - "{{ item.networks.0.dns_servers.0 }}"
    customization:
      autologon: yes
      password: "{{ winrm_password }}"
  with_items:
    "{{ vms }}"
  when:
    - vms[item].networks.dns_servers.1 is not defined
  delegate_to: localhost

- name: Clone the template with two DNS entries
  vmware_guest:
    hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password}}"
    validate_certs: False
    name: "{{ item.name }}"
    template: "{{ template_name }}"
    datacenter: "{{ vcenter_datacenter }}"
    folder: "{{ item.folder }}"
    state: poweredon
    cluster: "{{ vcenter_cluster }}"
    networks:
      - name: "{{ item.networks.0.name }}"
        ip: "{{ item.networks.0.ip }}"
        netmask: "{{ item.networks.0.netmask }}"
        gateway: "{{ item.networks.0.gateway }}"
        domain: "{{ item.networks.0.domain }}"
        dns_servers:
        - "{{ item.networks.0.dns_servers.0 }}"
        - "{{ item.networks.0.dns_servers.1 }}"
    customization:
      autologon: yes
      password: "{{ winrm_password }}"
  with_items:
    "{{ vms }}"
  when:
    - vms[item].networks.dns_servers.0 is defined and vms[item].networks.dns_servers.1 is defined
  delegate_to: localhost