---
plugin: vmware_vm_inventory
strict: False
hostname: 192.168.1.26
username: administrator@bootstrap.mil
password: VMware1!
validate_certs: False
with_tags: True
properties:
- 'guest.ipAddress'
- 'config.name'
compose:
  ansible_host: 'guest.ipAddress'
  composed_var: 'config.name'
groups:
  VMs: True
hostnames:
- config.name
keyed_groups:
- key: tags
  separator: ''
filters:
- guest.ipAddress is defined and (guest.ipAddress is match('172.16..11*'))

