---
# tasks file for dc
- name: Install ADDomainController DSC resource
  win_psmodule:
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    name: ActiveDirectoryDsc
    state: present

- name: Create jinja2 task file for Root PDC
  template:
    src: 'templates/dc.j2'
    dst: 'tasks/dc.yml'

- name: Import Root PDC task
  include_tasks: 'tasks/dc.yml'