---

- name: Install ADDomainController DSC resource
  win_psmodule:
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    name: ADDomainController
    state: present

- name: install Root PDC
  win_dsc:
    resource_name: ADDomainController
    DomainName: "{{ domain_name }}"
    domain_netbios_name: "{{ netbios_domain }}"
    SafemodeAdministratorPassword: "{{ safe_mode_password }}"
  no_log: no
  register: ad

- name: reboot server
  win_reboot:
    msg: "Installing AD. Rebooting..."
    pre_reboot_delay: 15
    reboot_timeout: 600
    post_reboot_delay: 420
  when: ad.changed
